version: '3'

services:
  monitor_server_livestream:
    build: 
      context: .
      dockerfile: client.Dockerfile
    network_mode: "host"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Asia/Jakarta
    command: python Client.py